services:
  redis:
    image: redis:6.2.6
    ports:
      - "0.0.0.0:6379:6379"

  sequencer:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    environment:
      - HEAT_BEAT_PRIVATE_KEY=$HEAT_BEAT_PRIVATE_KEY
      - HEAT_BEAT_LIMIT_NUM=$HEAT_BEAT_LIMIT_NUM
    ports:
      - "0.0.0.0:8587:8547"
      - "0.0.0.0:8588:8548"
      - "0.0.0.0:9682:9642"
    volumes:
      - "seqdata:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
      - "tokenbridge-data:/tokenbridge-data"
    command: --conf.file /config/sequencer_config.json --node.feed.output.enable --node.feed.output.port 9642 --node.batch-poster.max-size 80960 --execution.sequencer.max-tx-data-size 70000  --http.api net,web3,eth,txpool,debug --node.seq-coordinator.my-url  ws://sequencer:8548 --graphql.enable --graphql.vhosts * --graphql.corsdomain *

  sequencer_b:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8647:8547"
      - "0.0.0.0:8648:8548"
    volumes:
      - "seqdata_b:/home/user/.arbitrum/local/nitro"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_b:8548
    depends_on:
      - redis

  sequencer_c:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8747:8547"
      - "0.0.0.0:8748:8548"
    volumes:
      - "seqdata_c:/home/user/.arbitrum/local/nitro"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_c:8548
    depends_on:
      - redis

  sequencer_d:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8847:8547"
      - "0.0.0.0:8848:8548"
    volumes:
      - "seqdata_d:/home/user/.arbitrum/local/nitro"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_d:8548
    depends_on:
      - redis

  staker-unsafe:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8047:8547"
      - "0.0.0.0:8048:8548"
    volumes:
      - "unsafestaker-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/unsafe_staker_config.json
    depends_on:
      - sequencer
      - redis
      - validation_node

  poster:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8147:8547"
      - "0.0.0.0:8148:8548"
    volumes:
      - "poster-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  poster_b:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:9147:8547"
      - "0.0.0.0:9148:8548"
    volumes:
      - "poster-data-b:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  poster_c:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:9247:8547"
      - "0.0.0.0:9248:8548"
    volumes:
      - "poster-data-c:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  validator:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8247:8547"
      - "0.0.0.0:8248:8548"
    volumes:
      - "validator-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/validator_config.json --http.port 8547 --http.api net,web3,arb,debug --ws.port 8548
    depends_on:
      - sequencer
      - validation_node

  validation_node:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/nitro-val
    ports:
      - "0.0.0.0:8949:8549"
    volumes:
      - "config:/config"
    command: --conf.file /config/validation_node_config.json

  scripts:
    build: scripts/
    environment:
      - L1_RPC_URL=$L1_RPC_URL
      - L1_MNEMONIC=$L1_MNEMONIC
      - L2_CHAIN_ID=$L2_CHAIN_ID
    volumes:
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
      - "tokenbridge-data:/tokenbridge-data"

  relay:
    pid: host
    image: shard-node
    entrypoint: /usr/local/bin/relay
    ports:
      - "0.0.0.0:9652:9652"
    command: --chain.id 412346 --node.feed.input.url ws://sequencer:9642 --node.feed.output.port 9652

  tokenbridge:
    depends_on:
      - sequencer
    pid: host
    build:
      context: tokenbridge/
      args:
        TOKEN_BRIDGE_BRANCH: ${TOKEN_BRIDGE_BRANCH:-}
    environment:
      - ARB_URL=http://sequencer:8547
      - ETH_URL=$L1_HTTP_RPC_URL
    volumes:
      - "tokenbridge-data:/workspace"
      - /var/run/docker.sock:/var/run/docker.sock

  rollupcreator:
    depends_on:
      - sequencer
    pid: host
    build:
      context: rollupcreator/
      args:
        NITRO_CONTRACTS_BRANCH: ${NITRO_CONTRACTS_BRANCH:-}
    volumes:
      - "config:/config"
      - /var/run/docker.sock:/var/run/docker.sock

  datool:
    image: shard-node
    entrypoint: /usr/local/bin/datool
    volumes:
      - "config:/config"
      - "das-committee-a-data:/das-committee-a"
      - "das-committee-b-data:/das-committee-b"
      - "das-mirror-data:/das-mirror"

  das-committee-a:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/daserver
    ports:
      - "0.0.0.0:9876:9876"
      - "0.0.0.0:9877:9877"
    volumes:
      - "config:/config"
      - "das-committee-a-data:/das"
    command:
      - --conf.file=/config/l2_das_committee.json

  das-committee-b:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/daserver
    ports:
      - "0.0.0.0:8876:9876"
      - "0.0.0.0:8877:9877"
    volumes:
      - "config:/config"
      - "das-committee-b-data:/das"
    command:
      - --conf.file=/config/l2_das_committee.json

  das-mirror:
    pid: host # allow debugging
    image: shard-node
    entrypoint: /usr/local/bin/daserver
    ports:
      - "0.0.0.0:7877:9877"
    volumes:
      - "config:/config"
      - "das-mirror-data:/das"
    command:
      - --conf.file=/config/l2_das_mirror.json

volumes:
  l1keystore:
  seqdata:
  seqdata_b:
  seqdata_c:
  seqdata_d:
  unsafestaker-data:
  validator-data:
  poster-data:
  poster-data-b:
  poster-data-c:
  config:
  tokenbridge-data:
  das-committee-a-data:
  das-committee-b-data:
  das-mirror-data:
