services:
  postgres:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "0.0.0.0:7432:5432"

  redis:
    image: redis:6.2.6
    ports:
      - "0.0.0.0:6379:6379"

  sequencer:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8587:8547"
      - "0.0.0.0:8588:8548"
      - "0.0.0.0:9642:9642"
    volumes:
      - "seqdata:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
      - "tokenbridge-data:/tokenbridge-data"
    command: --conf.file /config/sequencer_config.json --node.feed.output.enable --node.feed.output.port 9642  --http.api net,web3,eth,txpool,debug --node.seq-coordinator.my-url  ws://sequencer:8548 --ws.addr "0.0.0.0" --ws.origins "*" --graphql.enable --graphql.vhosts * --graphql.corsdomain *


  sequencer_b:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8647:8547"
      - "0.0.0.0:8648:8548"
    volumes:
      - "seqdata_b:/home/user/.arbitrum/local/nitro"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_b:8548
    depends_on:
      - redis

  sequencer_c:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8747:8547"
      - "0.0.0.0:8748:8548"
    volumes:
      - "seqdata_c:/home/user/.arbitrum/local/nitro"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_c:8548
    depends_on:
      - redis

  sequencer_d:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8847:8547"
      - "0.0.0.0:8848:8548"
    volumes:
      - "seqdata_d:/home/user/.arbitrum/local/nitro"
      - "config:/config"
    command: --conf.file /config/sequencer_config.json --node.seq-coordinator.my-url ws://sequencer_d:8548
    depends_on:
      - redis

  staker-unsafe:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8047:8547"
      - "0.0.0.0:8048:8548"
    volumes:
      - "unsafestaker-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/unsafe_staker_config.json
    depends_on:
      - sequencer
      - redis
      - validation_node

  poster:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8147:8547"
      - "0.0.0.0:8148:8548"
    volumes:
      - "poster-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  poster_b:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:9147:8547"
      - "0.0.0.0:9148:8548"
    volumes:
      - "poster-data-b:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  poster_c:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:9247:8547"
      - "0.0.0.0:9248:8548"
    volumes:
      - "poster-data-c:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - redis

  validator:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro
    ports:
      - "0.0.0.0:8247:8547"
      - "0.0.0.0:8248:8548"
    volumes:
      - "validator-data:/home/user/.arbitrum/local/nitro"
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
    command: --conf.file /config/validator_config.json --http.port 8547 --http.api net,web3,arb,debug --ws.port 8548
    depends_on:
      - sequencer
      - validation_node

  validation_node:
    pid: host # allow debugging
    image: nitro-node
    entrypoint: /usr/local/bin/nitro-val
    ports:
      - "0.0.0.0:8949:8549"
    volumes:
      - "config:/config"
    command: --conf.file /config/validation_node_config.json

  scripts:
    build: scripts/
    environment:
      - SHARD_ADMIN_ADDRESS=$SHARD_ADMIN_ADDRESS
      - SHARD_ADMIN_PRIVATE_KEY=$SHARD_ADMIN_PRIVATE_KEY
      - SHARD_VALIDATOR_ADDRESS=$SHARD_VALIDATOR_ADDRESS
      - SHARD_SEQUENCER_ADDRESS=$SHARD_SEQUENCER_ADDRESS
      - GET_SHARD_CHAIN_ID_URL=$GET_SHARD_CHAIN_ID_URL
      - L2_RPC_URL=$L2_RPC_URL
    volumes:
      - "l1keystore:/home/user/l1keystore"
      - "config:/config"
      - "tokenbridge-data:/tokenbridge-data"

  relay:
    pid: host
    image: nitro-node
    entrypoint: /usr/local/bin/relay
    ports:
      - "0.0.0.0:9652:9652"
    command: --chain.id 412346 --node.feed.input.url ws://sequencer:9642 --node.feed.output.port 9652

  rollupcreator:
    depends_on:
      - sequencer
    pid: host
    build:
      context: rollupcreator/
      args:
        NITRO_CONTRACTS_BRANCH: ${NITRO_CONTRACTS_BRANCH:-}
    volumes:
      - "config:/config"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  consensus:
  l1keystore:
  seqdata:
  seqdata_b:
  seqdata_c:
  seqdata_d:
  unsafestaker-data:
  validator-data:
  poster-data:
  poster-data-b:
  poster-data-c:
  config:
  postgres-data:
  tokenbridge-data:
